### ISSUE TITLE
Default Result<MyClass> shouldn't be Success

### ISSUE THREAD

**Issue by tesar-tech** [jscarle/LightResults#18]
Consider this (valid) code:

```csharp
MyClass myClass = new();
myClass.CheckSuccess();//checks the result without assigning anything to the result variable

public class MyClass
{
    public void CheckSuccess()
    {
        if(result.IsSuccess(out var value))
            Console.WriteLine($"{value.SomeProp}");
    }
    
    public void Asign()//this is only here to make the warning disappear
    {
        result = Result.Ok(this);
    }
    Result<MyClass> result;
    public string SomeProp { get; set; } = "Hej";
}
```
Which throws ` System.NullReferenceException` 
Because the Result class check for absence of the errors, it present itself as successful even if the value is null.

I agree the sample isn't well designed code, but LightResults shouldn't allow throwing such exception. 

Also the workaround here is pretty simple - just assign failed result.

There are some solution to this problem - probably the best one would be to start the Result with an error and remove it on Result creation. 

If you give me green light I can work on it.

**Comment by jscarle** [comment]
The issue is due to the behavior of value types, and starting with version 9.x, `Result` is no longer a `class` but is now a `struct`. I've reworked the initialization logic to make it follow the default behavior of a `bool`, so now an uninitialized `Result` will now default to a failed state.

Changes published as [9.0.0-preview.5](https://www.nuget.org/packages/LightResults/9.0.0-preview.5).
