### ISSUE TITLE
A few issues with the API vs FluentResults

### ISSUE THREAD

**Issue by codewisdom** [jscarle/LightResults#37]
I really like what you are trying to achieve - aim for performance and retain the control and expressiveness of using Result.  I'm curious if you've looked into:

* Finding being forced to specify my return type always vs. FluentResults is jaring.  Have you checked the impact of implicit conversion on performance? [Implicit conversion from T to success result Result<T>](https://github.com/altmann/FluentResults?tab=readme-ov-file#implicit-conversion-from-t-to-success-result-resultt)

* The Try implementation is interesting, but without Bind I have no way to create a pipeline (I know this applies to your extensions).

* I'd like to pass an array of strings to Fail like with FluentResults.  Am I missing some easy way around this?

**Comment by codewisdom** [comment]
I figured out the last part by projecting to an IEnumerable of errors.

**Comment by jscarle** [comment]
The implicit cast was added in v9.0 (which is still in preview), but the lack of it in v8.0 was an oversight. I've since corrected it and it's been released on NuGet as v8.0.11.

As for the bind, it's on my roadmap to design a pipeline API with Match and Bind, probably won't be able to get around it for a little bit still though.
